application: webglearthapp
version: 1
runtime: python27
api_version: 1
threadsafe: false

# default_expiration: "24h"

handlers:
- url: (.*)/
  static_files: static\1/index.html
  upload: static/index.html

# allow CORS only on the /v2 for now
- url: /v2
  static_dir: static/v2
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /
  static_dir: static
